DiamondLightSource/FastCS

.devcontainer/devcontainer.json
.github/workflows/code.yml
.gitignore
Dockerfile
docs/_templates/custom-class-template.rst
docs/_templates/custom-module-template.rst
docs/conf.py
docs/user/reference/api.rst
pyproject.toml
src/fastcs/asyncio_backend.py
src/fastcs/attributes.py
src/fastcs/backend.py
src/fastcs/backends/__init__.py
src/fastcs/backends/asyncio_backend.py
src/fastcs/backends/epics/backend.py
src/fastcs/backends/epics/docs.py
src/fastcs/backends/epics/gui.py
src/fastcs/backends/epics/ioc.py
src/fastcs/connections.py
src/fastcs/controller.py
src/fastcs/cs_methods.py
src/fastcs/datatypes.py
src/fastcs/exceptions.py
src/fastcs/mapping.py
src/fastcs/wrappers.py

This includes the basic features of FastCS, including:
- Attributes and attribute parameters
- Wrappers and Handler classes for control system interactions
- EPICS backend, including interactive terminal
This repository works with the following branches:
Demo: https://github.com/MJGaughran/demo-fast-cs/tree/fast-cs-prototype
PVI fixes: https://github.com/epics-containers/pvi/tree/fast-cs-hacks

FastCS basic features

---

src/fastcs/backends/epics/gui.py
src/fastcs/backends/epics/ioc.py
src/fastcs/datatypes.py

This adds support for a `String` `DataType`.
The EPICS backend creates `longString{In,Out}` records and `Text{Read,Write}` widgets for `String`s.
Up for discussion whether we want to use `stringin` and `stringout` records in some circumstances. My current thinking is we just use long strings for everything and then we never have to worry about character limits. I don't think there are any downsides to this.

String DataType

---

pyproject.toml
src/fastcs/attributes.py
src/fastcs/backends/epics/gui.py
src/fastcs/controller.py
src/fastcs/cs_methods.py
src/fastcs/datatypes.py
src/fastcs/wrappers.py

@MJGaughran I will leave this open and merge it when I next start on another set of changes. If you get a chance to look at it that would be great. No worries if not.
The accompanying change to the [demo](https://github.com/DiamondLightSource/demo-fast-cs/pull/9/commits/ef13f4e26b38552b08f96b693258caa5757ea956) may help.
With grouping the generated UI looks like this:

Implement grouping of Attributes on generated UIs

---

src/fastcs/backends/epics/gui.py

Fixes button for bool AttrW which was showing up as a text entry

Fixes button for bool AttrW

---

src/fastcs/backends/epics/gui.py

Example usage: https://github.com/DiamondLightSource/odin-fastcs/commit/a042360e0ca1c1908722133bf07837083ee4d3f0

Add API to set title of generated UI

---

src/fastcs/backends/epics/gui.py
tests/backends/epics/test_gui.py

An extra `:` was inserted in the case where `attr_path` was empty.

Fix GUI PVs with no attribute path

---

pyproject.toml
src/fastcs/backends/__init__.py
src/fastcs/backends/tango/backend.py
src/fastcs/backends/tango/dsr.py
tests/backends/tango/test_dsr.py
tests/conftest.py

- I have made forks of Martin’s demo and fastcs respectively 
- https://github.com/marcelldls/FastCS
- https://github.com/marcelldls/demo-fast-cs
- Gary has given an initial review and I have included his feedback
You can run the demo by:
- Checking out the tango branches of fastcs and the demo
- Spinning up a tango control system 
- `yum install podman-compose`
- `podman-compose up` from the demo directory
- From the dev container
- Start the tickit device via the vscode debug launch
- Start tango device server by running `test-demo` from the command line
You can interact with the device in the following manners:
- Via an interactive python terminal:
- Run `itango3` from the dev container
- Create device proxy: `dev = DeviceProxy("my/device/name")`
- then you can use auto complete on dev …

Tango backend attempt

---

src/fastcs/backend.py
src/fastcs/backends/epics/gui.py
src/fastcs/controller.py
src/fastcs/mapping.py
tests/backends/epics/test_gui.py
tests/test_controller.py

Store sub controllers in a dictionary by path. This enables a Controller to introspect its SubControllers and their parmeters to perform higher level logic, such as fanning out configuration or creating Attributes that give a summary of underlying state (e.g. sum(), any(), all()).
Add some exception handling.

Add structure to SubController hierarchy

---

src/fastcs/backend.py
src/fastcs/backends/asyncio_backend.py
src/fastcs/backends/epics/backend.py
src/fastcs/backends/epics/ioc.py
src/fastcs/backends/tango/backend.py
src/fastcs/backends/tango/dsr.py
src/fastcs/controller.py
tests/backends/epics/test_gui.py
tests/backends/epics/test_ioc.py
tests/backends/tango/test_dsr.py
tests/conftest.py
tests/test_attribute.py
tests/test_backend.py

Fixes #17 
I have added https://github.com/DiamondLightSource/FastCS/issues/50 to resolve issues with the Tango backend caused / provoked by this change.

Enable controller initialisation on main event loop

---

src/fastcs/backend.py

This will avoid clashes when multiple Backends are used in future.

Convert Backend class attributes to instance attributes

---

src/fastcs/attributes.py
src/fastcs/backends/epics/ioc.py
src/fastcs/cs_methods.py
src/fastcs/mapping.py
tests/backends/epics/test_ioc.py

Appears to work now, have included some tests.
Added an enabled flag to the Attribute class, so that when EpicsIOC is called -> calls _create_and_link_attribute_pvs -> attributes can get set to `enabled=False`. I initially tried to delete the attribute and remove it from the mapping (see first commit) but this approach seems simpler. It's not sufficient to prevent the creation of the PV, as the epics gui.py calls _get_single_mapping which still creates the gui control component if we do not check for `enabled` or remove it from the SingleMapping.

Disable EPICS attributes and commands with too-long PV names

---

src/fastcs/backend.py
tests/test_backend.py

```
[:)] python -m fastcs_eiger ioc EIGER
INFO: PVXS QSRV2 is loaded, permitted, and ENABLED.
2024-11-18T16:13:59.846533809 WARN pvxs.tcp.setup Server unable to bind port 5075, falling back to [::]:37927
Starting iocInit
############################################################################
############################################################################
`update` AFTER 0.3049039840698242
`update` AFTER 0.41122913360595703
```
Futures start at the right time, and closing them with `stop_scan_futures` works the same way.

swapped back to using `Future`s

---

src/fastcs/backends/epics/backend.py
src/fastcs/backends/epics/ioc.py

pass ioc options to `EpicsIOC.__init__` instead of `run`

---

pyproject.toml
src/fastcs/attributes.py
src/fastcs/backend.py
src/fastcs/backends/epics/ioc.py
src/fastcs/datatypes.py
tests/backends/epics/test_ioc.py

81 add features to attributes and datatypes

---

src/fastcs/launch.py
tests/test_launch.py

`version` is a useful cli command - this option adds the command if the developer passes a version that should be output when executing `${my_fastcs_device} version`

Add optional version command to launcher

---

src/fastcs/controller.py
tests/test_controller.py

Change how we search for attributes

---

src/fastcs/transport/epics/ioc.py
tests/transport/epics/test_ioc.py

Closes #99
`builder.Action` is a wrapper to a `boolOut` with `always_update=True`. This is how PandaBlocks-ioc does it and will probably work with ophyd-async.
@dperl-dls can you please test this branch? (or if it's too much of a pain with updating alongside other changes then copy [the line](https://github.com/DiamondLightSource/FastCS/blob/5708b391d2a081fa1d8fdba6ae640ad871b00ea1/src/fastcs/transport/epics/ioc.py#L358-L361) where I do `aOut -> Action` locally.

Changed from `builder.aOut` to `builder.Action` for commands

---

src/fastcs/attributes.py
tests/test_attribute.py

This allows creating Attributes without a Handler for parameters that are only used for internal controller logic and not sent directly to a device.
Fixes #101

Add SimpleHandler to make minimal Attributes functional

---

tests/transport/tango/test_dsr.py

fixes #83 
Suppress the log messages dumped at the end of testing:
```
...
==================================================================== 53 passed in 5.11s =====================================================================
2024-11-28T14:50:44,795737+0000 INFO (dsr.py:26) test/nodb/assertablecontroller called fget method: ReadInt
2024-11-28T14:50:44,799603+0000 INFO (dsr.py:26) test/nodb/assertablecontroller called fget method: ReadWriteInt
2024-11-28T14:50:44,802900+0000 INFO (dsr.py:44) test/nodb/assertablecontroller called fset method: ReadWriteInt
2024-11-28T14:50:44,804099+0000 INFO (dsr.py:26) test/nodb/assertablecontroller called fget method: ReadWriteInt
2024-11-28T14:50:44,809197+0000 INFO (dsr.py:26) test/nodb/assertablecontroller called fget method: ReadWriteFloat …
```

Surpress tango test logging

---

src/fastcs/attributes.py
src/fastcs/backend.py
src/fastcs/transport/epics/util.py
tests/test_launch.py
tests/transport/epics/test_ioc.py

Sleeping after the scan coroutines means that in principle this is a constant delay rather than a fixed period

Coro sleep timing

---

src/fastcs/transport/epics/gui.py
src/fastcs/transport/epics/options.py

Currently the default epics options set an absolute file path. For example:
```
@dataclass
class EpicsDocsOptions:
path: Path = Path.cwd()  # The subject of this PR
depth: int | None = None
```
This means that the resulting schema depends on the host and execution context:
```
"EpicsDocsOptions": {
"properties": {
"path": {
"default": "/workspaces/thorlabs-mff-fastcs",  # Changes dynamically
"format": "path",
"title": "Path",
"type": "string"
},
"depth": {
"anyOf": [
{
"type": "integer"
},
{
"type": "null"
}
],
"default": null,
"title": "Depth"
}
},
```
Here it is proposed to rather use a relative path. This does not prevent an absolute path being passed. It allows the same functionality as before but with a consistent schema and additionally allows to make alterations to the relative …

Fix for default file paths

---

src/fastcs/launch.py
tests/test_launch.py

The reason to propose this change is because it is more consistent with the existing DLS python template project which reduces conflicts that need to be resolved

Change to --version for controller CLI

---

src/fastcs/launch.py
tests/data/schema.json
tests/test_launch.py

This adds a `get_controller_schema` function that can be convenient for assessing the schema of a controller - useful for the testing of a FastCS project. Another benefit is that the `tests/data/schema.json` is now also assessed by the new test - so the test will fail if its not kept up to date

Add get_controller_schema function

---

src/fastcs/attributes.py
src/fastcs/backend.py
src/fastcs/transport/epics/ca/ioc.py
src/fastcs/transport/epics/pva/_pv_handlers.py
tests/test_attribute.py
tests/transport/epics/ca/test_softioc.py

* Transports will add an update callback, so if we don't allow for multiple then running them simultaneously won't work.
* The controller level can add their own now too.

fix: Allowed multiple update callbacks on an `AttrR`

---

src/fastcs/transport/epics/pva/pvi_tree.py
tests/transport/epics/pva/test_p4p.py

Unlike controllers, attributes should not be grouped in the pva pvi tree.

fix: Prevent grouping attributes in the pva pvi.

---

src/fastcs/datatypes.py
src/fastcs/transport/epics/ca/ioc.py
src/fastcs/transport/epics/ca/util.py
src/fastcs/transport/epics/gui.py
src/fastcs/transport/epics/pva/types.py
tests/transport/epics/ca/test_softioc.py
tests/transport/epics/ca/test_util.py

Closes #150
May need to add test? Note that I have tested this change against a WIP version of fastcs-eiger running against slightly reworked branch of FastCS #134.
Records with the Enum datatype whose enum_cls have more than 16 members now use `longStringIn`/`longStringOut` records instead of `longIn`/`longOut`, this allows us to still have labelled dropdowns and string readbacks

CA enums with more than 16 values backed by string record

---

src/fastcs/attributes.py
src/fastcs/backend.py
src/fastcs/controller.py
tests/assertable_controller.py
tests/conftest.py
tests/test_attribute.py
tests/transport/epics/ca/test_softioc.py
tests/transport/graphQL/test_graphQL.py
tests/transport/rest/test_rest.py
tests/transport/tango/test_dsr.py

Resolves #59 
Added default initialise methods to Sender and Updater base classes.
Added initialise method to Attribute, checks for handler and calls the method.
Moved initialise into BaseController class, loops over attributes calling initialise with a reference to self.
Added unit test for Attribute class.
Fixes #59 
Fixes #130

Add Handler.initialise(controller)

---

src/fastcs/transport/epics/gui.py
src/fastcs/transport/epics/pva/adapter.py
src/fastcs/util.py
tests/test_util.py
tests/transport/epics/ca/test_gui.py
tests/transport/epics/pva/test_pva_gui.py

#Fixes #166
This PR adds `PvaEpicsGui`, which allows tables and prepends `pva://` to pvs to allow access to pva signals via the GUI. Tables already have this added, so this [issue](https://github.com/epics-containers/pvi/pull/147) in `pvi` should be merged.

Add table support in pva and fix gui pv naming

---

src/fastcs/datatypes.py
tests/test_attribute.py
tests/test_datatypes.py
tests/transport/epics/ca/test_util.py

Update DataType.validate to attempt cast

---

src/fastcs/attributes.py
tests/example_p4p_ioc.py
tests/test_attribute.py

fixes #126 
This removes use of `SimpleHandler` from `AttrW` and defaults it in `AttrRW`. Testing `AttrW` with this handler has been removed, and testing with `AttrRW` amended to check we can read the value we set.

Use SimpleHandler on AttrRW only

---

src/fastcs/backend.py
src/fastcs/util.py
tests/test_util.py

assert hinted attrs are bound and have right dtype after initialisation

---

src/fastcs/transport/epics/ca/adapter.py
tests/transport/epics/ca/test_softioc.py

fixes #190 
This PR adds softioc commands to the ca transport context, allowing us to run commands like `dbl` etc.

Add softioc functions to ca context

---

src/fastcs/launch.py
src/fastcs/transport/__init__.py
src/fastcs/transport/epics/ca/adapter.py
src/fastcs/transport/epics/pva/adapter.py
src/fastcs/transport/graphql/adapter.py
src/fastcs/transport/rest/adapter.py
src/fastcs/transport/tango/adapter.py
src/fastcs/transport/transport.py
tests/example_p4p_ioc.py
tests/example_softioc.py
tests/test_launch.py
tests/transport/epics/ca/test_softioc.py
tests/transport/epics/pva/test_p4p.py
tests/transport/graphQL/test_graphql.py
tests/transport/rest/test_rest.py
tests/transport/tango/test_dsr.py

Merge TransportAdapter and TransportOptions
